source 'https://rubygems.org'

gem 'require_all'
gem 'cucumber'
gem 'rspec'
gem 'page-object'
gem 'faker'
gem 'data_magic'
gem 'page_navigation'
gem 'activerecord', '3.2.1'
gem 'factory_girl'
gem 'database_cleaner'
gem 'sqlite3'
gem 'nokogiri'
gem 'builder'
gem 'soap-object'